from __future__ import annotations

from pathlib import Path


def render_edge_nginx(registry: dict) -> str:
    edge = registry.get("edge") or {}
    apps = registry.get("apps") or []
    catch = (edge.get("catch_all") or "reject").lower()
    lines = [
        "# Generated by cursor/env-manager. Do not hand-edit on the VPS.",
        "# Copy into aicoder-nginx (baked image) or mount as the single edge config.",
        "# Policy: one process on :80/:443. Unknown Host headers are rejected, never Byte.",
        "",
        "events {}",
        "http {",
        "  include       mime.types;",
        "  default_type  application/octet-stream;",
        "  sendfile      on;",
        "  client_max_body_size 60m;",
        "",
    ]

    for app in apps:
        ident = str(app["id"]).replace("-", "_")
        upstream = app.get("upstream")
        if upstream:
            lines += [f"  upstream {ident}_app {{", f"    server {upstream};", "  }", ""]
        api = app.get("api_upstream")
        if api:
            lines += [f"  upstream {ident}_api {{", f"    server {api};", "  }", ""]

    if catch == "reject":
        lines += [
            "  server {",
            "    listen 80 default_server;",
            "    listen [::]:80 default_server;",
            "    server_name _;",
            "    default_type text/plain;",
            "    return 404 'unknown host. use a registered domain from env-manager.\\n';",
            "  }",
            "",
        ]

    for app in apps:
        domains = " ".join(app.get("domains") or [])
        if not domains:
            continue
        ident = str(app["id"]).replace("-", "_")
        lines += [
            f"  # {app.get('title') or app['id']}",
            "  server {",
            "    listen 80;",
            "    listen [::]:80;",
            f"    server_name {domains};",
            "    client_max_body_size 60m;",
            "",
            "    location /.well-known/acme-challenge/ {",
            "      root /var/www/html;",
            "    }",
            "",
        ]
        if app.get("api_upstream"):
            lines += [
                "    location /api/ {",
                f"      proxy_pass http://{ident}_api;",
                "      proxy_set_header Host $host;",
                "      proxy_set_header X-Forwarded-Proto $scheme;",
                "      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "      proxy_read_timeout 120s;",
                "    }",
                "",
            ]
        lines += [
            "    location / {",
            f"      proxy_pass http://{ident}_app;",
            "      proxy_http_version 1.1;",
            "      proxy_set_header Host $host;",
            "      proxy_set_header X-Forwarded-Proto $scheme;",
            "      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
            "      proxy_set_header Upgrade $http_upgrade;",
            '      proxy_set_header Connection "upgrade";',
            "      proxy_read_timeout 120s;",
            "    }",
            "  }",
            "",
        ]

    lines += ["}", ""]
    return "\n".join(lines)


def write_generated(registry: dict, dest: Path) -> Path:
    dest.mkdir(parents=True, exist_ok=True)
    path = dest / "edge-http.conf"
    path.write_text(render_edge_nginx(registry))
    return path
